export const HYDRATE_PLAYLIST = 'HYDRATE_PLAYLIST';
export const HYDRATE_ALL_PLAYLISTS = 'HYDRATE_ALL_PLAYLISTS';

export const alias = {
  READ_FEED_AND_HYDRATE_PLAYLIST: 'READ_FEED_AND_HYDRATE_PLAYLIST_ALIAS',
  READ_FEED_AND_HYDRATE_ALL_PLAYLISTS: 'READ_FEED_AND_HYDRATE_ALL_PLAYLISTS_ALIAS'
};
